### ISSUE TITLE
Gallery option needs tweaking

### ISSUE THREAD

**Issue by bfintal** [gambitph/Titan-Framework#268] opened 2015-08-28 15:16 UTC
1. Selecting multiple images for the second time stops the modal from closing
2. Selecting multiple images again should add them to the gallery

**Comment by igorbenic** [comment] 2015-09-11 00:50
I have rewritten the javascript on my fork so that the frame is opened only once. The problem is that the onclick event does not check if a frame is initialized already.

I have also implemented inside the javascript on the frame the open event where all the images previously selected will be selected inside the media uploader modal. 

I will create a pull request on that but I have encountered a possible problem that could appear when there are two or more gallery types on the same page. I have started implementing the parameter "id" into the whole open/close/selection events and when I am done with that I will create a pull request if this bug wont be fixed before that :)

**Comment by SiamKreative** [comment] 2016-01-13 08:54
Also, how to sort the uploaded images?

**Comment by gstricklind** [comment] 2016-02-27 05:39
Hey Gambit, I get this issue too. Also at #2, the selected images get added, but the previous images are no longer selected. So basically the user has to re-select ALL images in addition the ones that they may have been wanting to add to the gallery.

**Comment by igorbenic** [comment] 2016-03-09 15:43
Hello all, I am sorry for the late response. 

At the moment I moved on another gallery part and left that unfinished due to the project deadline I had to meet. I will try to look in my files and finish it anytime soon and push it here. If anyone did already fix that issue, do please say so ;)

**Comment by ReggieDuran** [comment] 2016-09-23 10:16
Sorry for taking this too long, we've fixed it and we've implemented it again. acb2db2d43911c5efa743f33beb624c957af7047

**Closed by ReggieDuran** 2016-09-23 10:16 UTC
Labels: bug
